version: '3.1'

services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: maestro
      POSTGRES_USER: maestro
      POSTGRES_DB: rd-terapias
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data